[package]
name = "advent_util"
version = "0.1.0"
authors = ["Jeffrey Yasskin <jyasskin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
num = "0.2.0"
